apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-care-app
  namespace: pet-care-app
  labels:
    app: pet-care-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: pet-care-app
  template:
    metadata:
      labels:
        app: pet-care-app
    spec:
      containers:
      - name: pet-care-app
        image: "${REGISTRY}:${IMAGE_TAG}"
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "core.settings"
        volumeMounts:
        - name: media-volume
          mountPath: /app/media
      volumes:
      - name: media-volume
        emptyDir: {}
